/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font Converter for emWin version 5.28                       *
*        Compiled Jan 30 2015, 16:40:45                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: xiudada.c                                             *
* Font:        »ªÎÄ¿¬Ìå                                              *
* Height:      23                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  23                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: F:\f1\emwin\STemWin\Software\fontCvt_install\zhong.txt*
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontxiudada;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Fontxiudada_5730[ 69] = { /* code 5730 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,___XXX__,________,
  ________,____XX__,________,
  ____XX__,____XX__,________,
  _____X__,____XX__,________,
  _____X__,____X___,________,
  _____X__,____X___,X_______,
  _____X__,_X__X_XX,XX______,
  _____XXX,_X__XX__,X_______,
  ___XXX__,_XXXX___,X_______,
  _____X__,XX__X__X,X_______,
  _____X_X,_X__X_XX,___X____,
  _____X_X,_X__X__X,___X____,
  _____XX_,_X______,___X____,
  ___XX___,_X______,___X____,
  __XX____,__X_____,_XXX____,
  ________,___XXXXX,XX______,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontxiudada_5F00[ 69] = { /* code 5F00 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,_____XXX,________,
  _______X,XXXXXX__,________,
  ________,X____X__,________,
  ________,_X___X__,________,
  ________,_X___X__,________,
  ________,_X__XXXX,XXXX____,
  ____XXXX,XXXX_X__,________,
  ________,_X___X__,________,
  ________,X____X__,________,
  ________,X____X__,________,
  ________,X____X__,________,
  _______X,X____X__,________,
  _______X,_____X__,________,
  ______X_,_____X__,________,
  _____X__,_____X__,________,
  ________,_____X__,________,
  ________,_____X__,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontxiudada_6084[ 69] = { /* code 6084 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  _____X__,___XXX__,________,
  ______X_,____XX__,X_______,
  ______X_,____XX__,XX______,
  ______X_,____XX__,X_______,
  ______X_,_XX_XXXX,________,
  ______XX,X_X_XX__,________,
  ___X__X_,X___XXXX,X_______,
  ___X__X_,__XXX___,X_______,
  __XX__X_,__X_____,X_______,
  __X___X_,__XXXX__,X_______,
  ______X_,__X_____,X_______,
  ______X_,__X_XX__,X_______,
  ______X_,__XX____,X_______,
  _____XX_,__X_____,X_______,
  _____X__,_XX_____,X_______,
  _____X__,_X____XX,X_______,
  _____X__,_______X,X_______,
  ________,________,X_______,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontxiudada_73AB[ 69] = { /* code 73AB */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,____XX__,________,
  ________,____XX__,________,
  _______X,X___X___,________,
  ____XXXX,___X____,________,
  ______X_,___X___X,XXX_____,
  ______X_,__XXXXX_,________,
  ______X_,_X___XX_,________,
  ______XX,XX___XX_,________,
  ____XXX_,__X__XX_,________,
  ______X_,___X_X__,________,
  ______X_,____XX__,________,
  ______X_,X___XX__,________,
  ______XX,___XXXX_,________,
  ____XX__,__XX__XX,________,
  __XXX___,XX_____X,XXX_____,
  ________,________,XXXXX___,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontxiudada_7470[ 69] = { /* code 7470 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,____XX__,________,
  ________,____X___,________,
  ________,X__X___X,XX______,
  _____XXX,___XXXX_,XX______,
  ______X_,_XX__X__,XX______,
  ______X_,__X__X__,X_______,
  ______X_,__XXXXX_,X_______,
  _____XXX,__X__X__,X_______,
  ______X_,__X_XXXX,X_______,
  ______X_,___XX___,X_______,
  ______X_,X___XX__,X_______,
  ______XX,___XX__X,_X______,
  _____X__,___XX_XX,X_X_____,
  __XXX___,__X_X_X_,________,
  ________,_X__X___,____X___,
  _______X,X___XX__,___XX___,
  ________,_____XXX,XXXX____,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontxiudada_7684[ 69] = { /* code 7684 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,______XX,________,
  ______XX,X____XX_,________,
  ______XX,_____X__,________,
  ______X_,_____X__,________,
  _____X__,____X___,XX______,
  _____XXX,X__XXXXX,XXX_____,
  ___XX___,XX_X____,_X______,
  ____X___,X_X_____,_X______,
  ____X___,X__XX___,_X______,
  ____XX__,X___XX__,_X______,
  ____X___,X____X__,XX______,
  ____X___,X_______,XX______,
  ____XXXX,X_______,X_______,
  ____X___,X_______,X_______,
  ________,_____X_X,X_______,
  ________,______XX,X_______,
  ________,______XX,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontxiudada_7B54[ 69] = { /* code 7B54 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  _______X,_____XX_,________,
  _______X,_____XXX,XX______,
  ______XX,XXX_X___,________,
  ______X_,___X_XX_,________,
  _____X_X,X_____X_,________,
  ____X___,__X_____,________,
  ________,_XXX____,________,
  ________,_X__X___,________,
  ________,X____X__,________,
  _______X,______XX,________,
  _____XX_,XXXX___X,XXXX____,
  ____XX__,________,XXX_____,
  __XX__XX,XXXXXXX_,________,
  _______X,_____XX_,________,
  _______X,_____X__,________,
  _______X,XXXXXX__,________,
  _______X,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontxiudada_7F9E[ 69] = { /* code 7F9E */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,_____XXX,________,
  ________,XX__XX__,________,
  ________,_X_X____,________,
  ________,___XXXXX,________,
  _______X,XXX_____,________,
  ________,__X__X__,________,
  _______X,XXXXX___,________,
  ________,_X____XX,________,
  ________,_XXXXXXX,________,
  ____XXXX,XX______,________,
  ________,X__XXXX_,________,
  _______X,_XX___XX,________,
  ______XX,__X___X_,________,
  ______X_,XXXXX_X_,________,
  _____X__,__X__XX_,________,
  ___XX___,_XXXXXXX,XXX_____,
  __X__XXX,X_______,________,
  _X______,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontxiudada_9759[ 69] = { /* code 9759 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  _____XX_,____XX__,________,
  ______X_,____X___,________,
  ______X_,___XXXXX,X_______,
  ____XXXX,X__X__XX,________,
  ______X_,__X___X_,________,
  _____XXX,_____XXX,XX______,
  ______X_,__XXXX__,XX______,
  ____XXXX,_____XXX,XXXX____,
  _XXX___X,XXXXXX__,X_______,
  _____XX_,X____X__,X_______,
  _____XXX,X___XXXX,XX______,
  _____X__,XXXX_X__,________,
  _____XXX,X____X__,________,
  ____X___,X____X__,________,
  ____X__X,X____X__,________,
  ____X__X,X____X__,________,
  ________,____XX__,________,
  ________,____X___,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_Fontxiudada_CharInfo[9] = {
   {  21,  21,  3, acGUI_Fontxiudada_5730 } /* code 5730 */
  ,{  21,  21,  3, acGUI_Fontxiudada_5F00 } /* code 5F00 */
  ,{  21,  21,  3, acGUI_Fontxiudada_6084 } /* code 6084 */
  ,{  21,  21,  3, acGUI_Fontxiudada_73AB } /* code 73AB */
  ,{  21,  21,  3, acGUI_Fontxiudada_7470 } /* code 7470 */
  ,{  21,  21,  3, acGUI_Fontxiudada_7684 } /* code 7684 */
  ,{  21,  21,  3, acGUI_Fontxiudada_7B54 } /* code 7B54 */
  ,{  21,  21,  3, acGUI_Fontxiudada_7F9E } /* code 7F9E */
  ,{  21,  21,  3, acGUI_Fontxiudada_9759 } /* code 9759 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontxiudada_Prop9 = {
   0x9759 /* first character */
  ,0x9759 /* last character  */
  ,&GUI_Fontxiudada_CharInfo[  8] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontxiudada_Prop8 = {
   0x7F9E /* first character */
  ,0x7F9E /* last character  */
  ,&GUI_Fontxiudada_CharInfo[  7] /* address of first character */
  ,&GUI_Fontxiudada_Prop9 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontxiudada_Prop7 = {
   0x7B54 /* first character */
  ,0x7B54 /* last character  */
  ,&GUI_Fontxiudada_CharInfo[  6] /* address of first character */
  ,&GUI_Fontxiudada_Prop8 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontxiudada_Prop6 = {
   0x7684 /* first character */
  ,0x7684 /* last character  */
  ,&GUI_Fontxiudada_CharInfo[  5] /* address of first character */
  ,&GUI_Fontxiudada_Prop7 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontxiudada_Prop5 = {
   0x7470 /* first character */
  ,0x7470 /* last character  */
  ,&GUI_Fontxiudada_CharInfo[  4] /* address of first character */
  ,&GUI_Fontxiudada_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontxiudada_Prop4 = {
   0x73AB /* first character */
  ,0x73AB /* last character  */
  ,&GUI_Fontxiudada_CharInfo[  3] /* address of first character */
  ,&GUI_Fontxiudada_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontxiudada_Prop3 = {
   0x6084 /* first character */
  ,0x6084 /* last character  */
  ,&GUI_Fontxiudada_CharInfo[  2] /* address of first character */
  ,&GUI_Fontxiudada_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontxiudada_Prop2 = {
   0x5F00 /* first character */
  ,0x5F00 /* last character  */
  ,&GUI_Fontxiudada_CharInfo[  1] /* address of first character */
  ,&GUI_Fontxiudada_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontxiudada_Prop1 = {
   0x5730 /* first character */
  ,0x5730 /* last character  */
  ,&GUI_Fontxiudada_CharInfo[  0] /* address of first character */
  ,&GUI_Fontxiudada_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_Fontxiudada = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,23 /* height of font  */
  ,23 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Fontxiudada_Prop1}
  ,18 /* Baseline */
  ,8 /* Height of lowercase characters */
  ,13 /* Height of capital characters */
};

